spring:
  application:
    name: tours-service
server:
  port: ${PORT:8086}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka/
  instance:
    hostname: ${DOMAIN_NAME:localhost}
    nonSecurePort: 80

